### PR TITLE
Fixes Outfits

### PR DESCRIPTION
**Pull request by erikmeyer08**
Fixes Outfits

### CODE REVIEW

**Comment by charj** [comment]
Code looks to be fine, however. I'm unaware of what this is fixing due to lack of description

**Comment by Qwerty1Verified** [comment]
> Code looks to be fine, however. I'm unaware of what this is fixing due to lack of description

It fixes the nil value data error that occurs when attempting to open the outfits menu. This is due to the code passing `Config.ClothingRooms` which is a number indexed table for the clothing locations rather then the outfits, replacing this with `Config.Outfits` correctly passes the outfit presets table for that job, the intended functionality is shown by the fact it attempts to index the locations by the `v.requiredJob`.

**Review by Qwerty1Verified — APPROVED** [review]
This change correctly renames the used table for the oufits. It fixes the nil value data error that occurs when attempting to open the outfits menu. This is due to the code passing `Config.ClothingRooms` which is a number indexed table for the clothing locations rather then the outfits, replacing this with `Config.Outfits` correctly passes the outfit pre-sets table for that job, the intended functionality is shown by the fact it attempts to index the locations by the `v.requiredJob`.

**Comment by charj** [comment]
Gotcha. Funny enough I reported this issue. https://github.com/qbcore-framework/qb-clothing/issues/169
Testing now.

**Comment by charj** [comment]
Before this patch:
image

**Comment by charj** [comment]
LGTM.
image

**Review by Z3rio — APPROVED** [review]

**Pull request merged**
