### PR TITLE
Job clothingrooms don't work

### PR DESCRIPTION
**Pull request by LV-Soft**
After the update, the **job clothingrooms** don't work...

Some conditions are wrong when creating the combozone

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **yes** (Be honest)
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**

### CODE REVIEW

**Review by HyperCheetah — CHANGES_REQUESTED** [review]
Attempt to index a nil value field "job"

**Review by r0adra93 — CHANGES_REQUESTED** [review]
This only partially resolves the issue.

The thread runs at resource start.

When the player logs into the game the thread can sometimes stop running.
To prevent this the threads need to be put into their own function then be called from on playerlogon and on resource start.

that will guarantee that the threads are running and allow for the E to popup without needing to restar tthe resource each time a player comes on.

**Comment by r0adra93** [comment]
I submitted a PR into your github.
Once you merge it in I will approve this PR.

**Review by r0adra93 — APPROVED** [review]

**Comment by MentalIllness** [comment]
Should be fixed in the current update.

**Pull request closed without merging**
