### PR TITLE
qb-jobs added support

### PR DESCRIPTION
**Pull request by r0adra93**
Added checks and exports to make it work with qb-jobs.

**Describe Pull request**
Added checks and exports to make it work with qb-jobs
function tprint removed as the linter flipped out stating it didn't exist.
I also reorganized the entire script
Variables with variables
functions with functions
events with events
threads with threads

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]

### CODE REVIEW

**Review by mrdiamonddirt — APPROVED** [review]
checked all 4 pull requests together worked no issues found,
https://github.com/qbcore-framework/qb-clothing/pull/157 
https://github.com/qbcore-framework/qb-target/pull/167
https://github.com/qbcore-framework/qb-garages/pull/263
https://github.com/qbcore-framework/qb-phone/pull/342

**Comment by r0adra93** [comment]
Added checks and exports to make it work with qb-jobs
function tprint removed as the linter flipped out stating it didn't exist.
I also reorganized the entire script
Variables with variables
functions with functions
events with events
threads with threads

**Comment by r0adra93** [comment]
The script had no exports and i needed to export data from qb-jobs to qb-clothing.

The script was a disorganized mess and i reorganized it.

**Comment by Z3rio** [comment]
@r0adra93 Ah sorry, my fault. The client.lua file didnt want to show itself due to your changes being too large haha.
So I only saw the config file initially, I will take a look at these 4 PRs.

**Review by Z3rio — APPROVED** [review]
Works fine when testing through:
- Creation of characters
- Clothing menu through admin menu
- Clothing shops

**Pull request merged**
